### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123",
  "name": "Jaeyeon"
}

> {%
    client.global.set("auth_token", response.body.accessToken);
%}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123",
  "name": "Jaeyeon"
}
